version: "3.7"
services:
  datascience-notebook:
    image:  jupyter/datascience-notebook
    volumes:
        - ./books:/home/jovyan/work:Z
    ports:
      - 8888:8888
    container_name: datascience-notebook-container
